### ISSUE TITLE
Mouse Input on Macs

### ISSUE THREAD

**Issue by shaendro** [sarahschuetz/Blockhalde#5]
I don't know the current state of the issue, but the most recent push should have eliminated the mouse input issues for Macs. Sadly, this fix relies on the CursorCatched functionality again, so I would need @urstruktur to test it out and report back if the rendering issues have returned.

**Comment by urstruktur** [comment]
thanks for asking. Issue is resolved, as the error was related to changed system resolution settings. 👍
