### ISSUE TITLE
Weird screen space noise on mac systems

### ISSUE THREAD

**Issue by tapirbug** [sarahschuetz/Blockhalde#6]
After launch, there is some weird glitchy overlay. From what I heard from others today, this bug can only be reproduced on mac systems.

It occurs before the first time the right click menu is opened and then never again.

Since the glitch sometimes shows parts of unrelated windows, it most likely stems from an uninitialized texture that is painted over the whole window.

This is how the bug looks like:
<img width="1392" alt="screen shot 2017-01-09 at 21 45 50" src="https://cloud.githubusercontent.com/assets/6675136/21782816/1b55e9fe-d6b5-11e6-88cb-f91fed4ee96d.png">

I'll try and fix this 😘

**Comment by tapirbug** [comment]
[This commit](https://github.com/sarahschuetz/Blockhalde/commit/e8e5ee12884206eb8af1b0cfad970a2cf07f198c) fixes the glitch by not painting the blurred background until `setVisible(boolean visible)` of [`BlurActor`](https://github.com/sarahschuetz/Blockhalde/blob/e8e5ee12884206eb8af1b0cfad970a2cf07f198c/core/src/com/blockhalde/gui/grid/BlurActor.java) is first called with a visible parameter of `true` and this check in the setter also succeeds: `RendererGUI.instance().menusActive == 1 && visible`

This effectively leads to the texture only being painted if it holds a valid texture.

**Comment by haslingera** [comment]
Thank you, Philipp, for correcting my mess! It probably would have taken me a long time to find the error 😄
